spring:
  profiles:
    active: prod
---
spring:
  profiles: dev
spring.datasource:
  url: jdbc:mysql://localhost:6306/springboot-db
  username: root
  password: password
  testWhileIdle: true
  validationQuery: SELECT 1
spring.jpa:
  show-sql: true
  hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

---

spring:
  profiles: prod
spring.datasource:
  url: jdbc:mysql://localhost:3306/springboot-db
  username: root
  password: password
  testWhileIdle: true
  validationQuery: SELECT 1
spring.jpa:
  show-sql: true
  hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

